### ISSUE TITLE
Ask about implement the PLUS !

### ISSUE THREAD

**Issue by vanvantong** [mami-project/plus-lib#1]
Dear administrator of plus-lib,

I am studying about PLUS and want to run some experiment on PLUS. Has your side done about building plus-lib completely?
If it is built completely, could you show me how to implement plus-lib? Could you share me it?

Thank you in advance!

**Comment by FMNSSun** [comment]
It may be subject to minor changes but should be fairly stable API-wise. See

https://github.com/mami-project/plus-lib/blob/master/HOWTO.md
